/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MySurvey {
        "cats": { category_code: number; category_name: string; }[];
    }
}
declare global {
    interface HTMLMySurveyElement extends Components.MySurvey, HTMLStencilElement {
    }
    var HTMLMySurveyElement: {
        prototype: HTMLMySurveyElement;
        new (): HTMLMySurveyElement;
    };
    interface HTMLElementTagNameMap {
        "my-survey": HTMLMySurveyElement;
    }
}
declare namespace LocalJSX {
    interface MySurvey {
        "cats"?: { category_code: number; category_name: string; }[];
    }
    interface IntrinsicElements {
        "my-survey": MySurvey;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-survey": LocalJSX.MySurvey & JSXBase.HTMLAttributes<HTMLMySurveyElement>;
        }
    }
}
